//jshint esversion:8
// code generated by chatgpt, fixed by wcyat
import { Client, Message } from "whatsapp-web.js";
import { ObjectId } from "mongodb";
import db from "../db/index.js";

interface GameState {
  board: string[][];
  currentPlayer: string;
}

interface GameDocument {
  _id?: ObjectId;
  chatId: string;
  gameState: GameState;
}

const execute = async (client: Client, msg: Message, args: string[]) => {
  const chatId = (await msg.getChat()).id._serialized;
  const command = args[0];

  if (command === "start") {
    const size = parseInt(args[1]) || 3;

    if (size < 3 || size > 10) {
      client.sendMessage(
        chatId,
        "Invalid board size. Please choose a size between 3 and 10."
      );
      return;
    }

    const gameCollection = db("ttt").coll;
    const existingGame = await gameCollection.findOne({ chatId });

    if (existingGame) {
      client.sendMessage(
        chatId,
        "A game is already in progress. Use `!ttt reset` to reset the current game."
      );
      return;
    }

    const gameState = getInitialGameState(size);
    const gameDoc: GameDocument = { chatId, gameState };

    await gameCollection.insertOne(gameDoc);
    client.sendMessage(chatId, "New Tic Tac Toe game started.");
    await printBoard(client, chatId);
    return;
  }

  if (command === "reset") {
    const gameCollection = db("ttt").coll;

    await gameCollection.deleteOne({ chatId });
    client.sendMessage(
      chatId,
      "Game reset. Start a new game with `!ttt start`."
    );
    return;
  }

  const gameDoc = await getGameDoc(chatId);
  if (!gameDoc) {
    client.sendMessage(
      chatId,
      "No Tic Tac Toe game in progress. Start a new game with `!ttt start`."
    );
    return;
  }

  const gameState = gameDoc.gameState;
  const { board, currentPlayer } = gameState;

  if (command === "play") {
    const rowIndex = parseInt(args[1]);
    const columnIndex = parseInt(args[2]);

    if (
      isNaN(rowIndex) ||
      isNaN(columnIndex) ||
      rowIndex < 0 ||
      columnIndex < 0 ||
      rowIndex >= board.length ||
      columnIndex >= board.length
    ) {
      client.sendMessage(
        chatId,
        "Invalid move. Please provide valid row and column indices."
      );
      return;
    }

    if (board[rowIndex][columnIndex] !== " ") {
      client.sendMessage(
        chatId,
        "Invalid move. The selected cell is already occupied."
      );
      return;
    }

    board[rowIndex][columnIndex] = currentPlayer;
    gameState.currentPlayer = currentPlayer === "X" ? "O" : "X";

    await updateGameState(chatId, gameState);
    await printBoard(client, chatId);

    const winner = getWinner(board);
    if (winner) {
      client.sendMessage(chatId, `Player ${winner} wins! Game over.`);
      await resetGame(chatId);
      return;
    }

    if (isBoardFull(board)) {
      client.sendMessage(chatId, "It's a draw! Game over.");
      await resetGame(chatId);
      return;
    }

    return;
  }

  client.sendMessage(
    chatId,
    "Invalid command. Use `!ttt start` to start a new game or `!ttt play [row] [column]` to make a move."
  );
};

const getInitialGameState = (size: number): GameState => {
  const board: string[][] = [];

  for (let i = 0; i < size; i++) {
    const row: string[] = [];

    for (let j = 0; j < size; j++) {
      row.push(" ");
    }

    board.push(row);
  }

  return {
    board,
    currentPlayer: "X",
  };
};

const printBoard = async (client: Client, chatId: string) => {
  const gameDoc = await getGameDoc(chatId);
  if (!gameDoc) {
    client.sendMessage(
      chatId,
      "No Tic Tac Toe game in progress. Start a new game with `!ttt start`."
    );
    return;
  }

  const gameState = gameDoc.gameState;
  const board = gameState.board;

  let boardString = "";
  for (let i = 0; i < board.length; i++) {
    boardString += board[i].join(" | ") + "\n";
    if (i < board.length - 1) {
      boardString += "--".repeat(board[i].length * 2 - 1) + "\n";
    }
  }

  client.sendMessage(chatId, "Current game state:\n" + boardString);
};

const getGameDoc = async (chatId: string): Promise<GameDocument | null> => {
  const gameCollection = db("ttt").coll;
  return (await gameCollection.findOne({ chatId })) as GameDocument;
};

const updateGameState = async (chatId: string, gameState: GameState) => {
  const gameCollection = db("ttt").coll;
  await gameCollection.updateOne({ chatId }, { $set: { gameState } });
};

const resetGame = async (chatId: string) => {
  const gameCollection = db("ttt").coll;
  await gameCollection.deleteOne({ chatId });
};

const getWinner = (board: string[][]): string | null => {
  const size = board.length;

  // Check rows
  for (let i = 0; i < size; i++) {
    const row = board[i];
    if (row.every((cell) => cell === row[0] && cell !== " ")) {
      return row[0];
    }
  }

  // Check columns
  for (let j = 0; j < size; j++) {
    const column = board.map((row) => row[j]);
    if (column.every((cell) => cell === column[0] && cell !== " ")) {
      return column[0];
    }
  }

  // Check diagonals
  const diagonal1 = board.map((row, i) => row[i]);
  if (diagonal1.every((cell) => cell === diagonal1[0] && cell !== " ")) {
    return diagonal1[0];
  }

  const diagonal2 = board.map((row, i) => row[size - i - 1]);
  if (diagonal2.every((cell) => cell === diagonal2[0] && cell !== " ")) {
    return diagonal2[0];
  }

  return null;
};

const isBoardFull = (board: string[][]): boolean => {
  return board.every((row) => row.every((cell) => cell !== " "));
};

export default {
  name: "tictactoe",
  command: "!ttt",
  description: "Play a game of Tic-Tac-Toe!",
  commandType: "plugin",
  isDependent: false,
  help: `*Tic-Tac-Toe Game Commands*:
  • Start a game: \`!ttt start [size]\` (default size is 3 if not provided)
  • Make a move: \`!ttt move [row] [column]\`
  • Reset the game: \`!ttt reset\`
  • Help: \`!ttt help\`
  `,
  execute,
  public: true,
};
