version: "3.9"

services:
  wtstodis:
    image: registry.gitlab.com/wcyat/whatsapp-to-discord
    container_name: wtstodis
    restart: unless-stopped
    volumes:
     - ./session.secure:/app/session.secure
    environment:
      SESSION_KEY: ${SESSION_KEY}
      PMPERMIT_ENABLED: ${PMPERMIT_ENABLED}
      MONGODB_URL: ${MONGODB_URL}
      DEFAULT_TR_LANG: ${DEFAULT_TR_LANG}
      ENABLE_DELETE_ALERT: ${ENABLE_DELETE_ALERT}
      OCR_SPACE_API_KEY: ${OCR_SPACE_API_KEY}
      WTS_GROUP_ID: ${WTS_GROUP_ID}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DISCORD_READ_CHANNEL_ID: ${DISCORD_READ_CHANNEL_ID}
      DISCORD_FORWARD_CHANNEL_ID: ${DISCORD_FORWARD_CHANNEL_ID}
      PING_URL: ${PING_URL}
