version: "3.9"

services:
  wtstodis:
    image: registry.gitlab.com/wcyat/whatsapp-to-discord
    container_name: wtstodis
    restart: unless-stopped
    volumes:
     - ./session.secure:/app/session.secure
     - ./.wwebjs_auth:/app/.wwebjs_auth
    environment:
      SESSION_KEY: ${SESSION_KEY}
      PMPERMIT_ENABLED: ${PMPERMIT_ENABLED}
      MARK_AS_SEEN: ${MARK_AS_SEEN}
      MONGODB_URL: "mongodb://${MONGO_USER}:${MONGO_PASSWORD}@wtstodis-mongo:${MONGO_PORT}"
      DEFAULT_TR_LANG: ${DEFAULT_TR_LANG}
      ENABLE_DELETE_ALERT: ${ENABLE_DELETE_ALERT}
      OCR_SPACE_API_KEY: ${OCR_SPACE_API_KEY}
      WTS_GROUP_ID: ${WTS_GROUP_ID}
      WTS_OWNER_ID: ${WTS_OWNER_ID}
      WTS_MEDIA_FORWARD_GROUP_ID: ${WTS_MEDIA_FORWARD_GROUP_ID}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DISCORD_READ_CHANNEL_ID: ${DISCORD_READ_CHANNEL_ID}
      DISCORD_FORWARD_CHANNEL_ID: ${DISCORD_FORWARD_CHANNEL_ID}
      DISCORD_TO_WHATSAPP: ${DISCORD_TO_WHATSAPP}
      WHATSAPP_TO_DISCORD: ${WHATSAPP_TO_DISCORD}
      DISCORD_OWNER_ID: ${DISCORD_OWNER_ID}
      BITLY_API_KEY: ${BITLY_API_KEY}
      TZ: ${TZ:-Asia/Hong_Kong}
    networks:
      - whatsbot-network
  wtstodis-mongo:
    container_name: wtstodis-mongo
    image: mongo
    tty: true
    command: mongod --auth --port=${MONGO_PORT} --bind_ip_all
    restart: always
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: whatsbot
    networks:
      - whatsbot-network
    volumes:
      - ./data:/data/db
networks:
  whatsbot-network:
    driver: bridge